name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - mohanboddu 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **NOTE** A large number of issues reported against Podman are often found to already be fixed in more current versions of the project.  Before reporting an issue, please verify the version you are running with `podman version` and compare it to the latest release documented on the top of Podman's [README.md](../README.md).If they differ, please update your version of Podman to the latest possible and retry your command before creating an issue.
        
        Also, there is a running list of known issues in the [Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md), please reference that page before opening a new issue.
        
        If you are filing a bug against `podman build`, please instead file a bug against Buildah (https://github.com/containers/buildah/issues). Podman build executes Buildah to perform container builds, and as such the Buildah maintainers are best equipped to handle these bugs.

        Commands you might need to run to create the issue
          $ podman version
          $ podman info
          $ rpm -q podman
  - type: dropdown
    id: podman_version
    attributes:
      label: Podman Version
      description: What version of our podman are you running?
      options:
        - main
        - 4.3
        - 4.2
        - 4.1
        - 4.0
        - 3.4
        - 3.3
        - 3.2
        - 3.1
        - 3.0
        - Other
    validations:
      required: true
  - type: input
    id: full_podman_version
    attributes:
      label: Full Podman Version
      description: Please enter the full version
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System 
      description: What operating system are you using?
      options:
        - Fedora
        - CentOS
        - RHEL
        - Ubuntu
        - Arch
        - MacOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: Operating System Version
      description: Please enter your Operating System Version
    validations:
      required: true
  - type: dropdown
    id: arch 
    attributes:
      label: Architecture 
      description: What architecture are you using to run podman?
      options:
        - x86_64 (Default)
        - aarch64
        - power
        - s390x
    validations:
      required: true
  - type: dropdown
    id: podman_in_a_container 
    attributes:
      label: Podman in a container 
      description: Please select Yes if you are running podman in a container
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: dropdown
    id: privileged_rootless
    attributes:
      label: Privileged Or Rootless
      description: Are you running the containers as privileged or non-root user?
      options:
        - Privileged
        - Rootless
  - type: dropdown
    id: upstream_latest
    attributes:
      label: Upstream Latest Release
      description: Have you tried running the [latest upstream release](https://github.com/containers/podman/releases/latest)
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please explain your issue
      value: "Describe your issue"
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce the issue
      description: Please explain the steps to reproduce the issue
      value: "Steps to reproduce the issue\n1.\n2.\n3.\n"
    validations:
      required: true
  - type: textarea
    id: received_results
    attributes:
      label: Describe the results you received
      description: Please explain the results you are noticing
      value: "Describe the results you received"
    validations:
      required: true
  - type: textarea
    id: expected_results
    attributes:
      label: Describe the results you expected
      description: Please explain the results you are expecting
      value: "Describe the results you expected"
    validations:
      required: true
  - type: textarea
    id: podman_info
    attributes:
      label: podman info output
      description: Please copy and paste podman info output.
      render: shell
  - type: textarea
    id: additional_info 
    attributes:
      label: Additional information
      description: Please explain the additional information you deem important
      value: "Additional information like issue happens only occasionally or issue happens when on a particular architecture or setting"
    validations:
      required: true
