name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - mohanboddu 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Podman Version
      description: What version of our podman are you running?
      options:
        - 4.3 (Default)
        - 4.2
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System 
      description: What operating system are you using?
      options:
        - Fedora (Default)
        - CentOS
        - RHEL
        - Ubuntu
        - Arch
        - MacOS
        - Windows
    validations:
      required: true
  - type: dropdown
    id: arch 
    attributes:
      label: Architecture 
      description: What architecture are you using to run podman?
      options:
        - x86_64 (Default)
        - aarch64
        - power
        - s390x
    validations:
      required: true
  - type: checkboxes
    id: podman_in_a_container 
    attributes:
      label: Podman in a container 
      description: Please check the box if you are running podman in a container
      options:
        - label: Running podman in a container
  - type: textarea
    id: description 
    attributes:
      label: Issue Description
      description: Please explain your issue
      value: "Description of the issue"
    validations:
      required: true
  - type: textarea
    id: podman_info
    attributes:
      label: podman info output
      description: Please copy and paste podman info output.
      render: shell
